# Generated by Django 5.2 on 2025-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuser',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communityuser',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityuser',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
