# Generated by Django 5.2 on 2025-05-04 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_communityuser_about_communityuser_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityposting',
            name='offerings',
            field=models.ManyToManyField(blank=True, related_name='postings', to='api.offering'),
        ),
        migrations.AlterField(
            model_name='communityposting',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='postings', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='offerings',
            field=models.ManyToManyField(blank=True, related_name='orders', to='api.offering'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
