# Generated by Django 5.2 on 2025-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reminder_is_deleted_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
